# Generated by Django 2.2 on 2020-12-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_enduserinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enduserprofile',
            old_name='endUser',
            new_name='user',
        ),
    ]
